### ISSUE TITLE
May i contribute?

### ISSUE THREAD

**Issue by AronasGITHUB** [VoltagedDebunked/nox#1]
Hello, call me aaron

I love coding in shell scripts, but also learning to be a web dev.
Can i monitor and help you improve your install.sh file? I want to make your autoinstaller a great expierience without many bugs. 
Your install.sh files will be tested by me, looking for any possible bugs. If i do find one, i may edit your install.sh file to add bug fixes.
Once i fixed many bugs, you/i/we could potentially create a new release that fixed bugs known by me and other users.

Not only will i hunt bugs in your install.sh file, but also improve the expierience of installing.

So, finally, can i contribute?

**Comment by VoltagedDebunked** [comment]
of course!
